# Apache2 on Ubuntu 18.04
---
- hosts: localhost
  become: true

  tasks:
    - name: Install prerequisites
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'aptitude' ]

    - name: Install Apache 2
      apt: name=apache2 update_cache=yes state=latest

    - name: Enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - Restart Apache2  

    - name: Copy index test page
      template:
        src: "files/index.html"
        dest: "/var/www/html/index.html"


  handlers:
    - name: Restart Apache2
      service:
        name: apache2
        state: restarted
